### ISSUE TITLE
Error converting value {null} to type 'System.Boolean'. Path 'data.authorization.reusable'

### ISSUE THREAD

**Issue by ibrahimlawal** [adebisi-fa/paystack-dotnet#1]
seems like on cancelation the value returned for the reusable field is null , so what happens is that its trying to pass a null to a Boolean value , hence the error. What fix would you suggest?

**Comment by adebisi-fa** [comment]
I'm presuming this applies to the ITransactionAPI.Verify(...) method. There are two solutions around this issue:

1. Make **reusable** return **false** (instead of **null**) from the API.

2. We can make the **data.authorization.reusable** nullable to accommodate the null value.

```c#
    . . .
    public bool? Reusable { get; set; }
   . . . 
```

Kindly advice on what's possible, please.  If option one isn't possible, we'll go for the second.  

Hope this helps.

**Comment by ibrahimlawal** [comment]
Since the transaction that caused the error was an abandoned one... In this case the user never provided card details hence the entirety of the authorizations object would have null values. I think it would be better to make reusable and other keys in the object nullable

-----Original Message-----
