### ISSUE TITLE
Enable callbackURL as a parameter on Transaction Initialize

### ISSUE THREAD

**Issue by Adekoreday** [adebisi-fa/paystack-dotnet#18]
`TransactionInitializeResponse Initialize(string email, int amount);` out of the box.
should support the optional callback URL. this is very important to allow users to get redirected to their platform after payment is made via PayStack.

Also, documentation should clearly state that the amount is in kobo.

could fix this with a PR though if you find it worthy.

**Comment by adebisi-fa** [comment]
Hello @Adekoreday,

Trust your compilers are cooperating!

Have you try using the request dto `TransactionInitializeRequest`, viz:

```C#
var response = _api.Initialize(new TransactionInitializeRequest {
    Email = "test@email.com",
    AmountInKobo = 45000, // This is for N450.00k
    CallbackUrl = "https://callback.domain.net/processor/path"
});
```
That would allow you to set all properties missing in the short-version of the `Initialize(...)` method.

Hope that helps.

 **- Foluso.**

**Comment by adebisi-fa** [comment]
I'm closing this issue, for now.  

Kindly re-open if there is any comment/reservation on the suggestion provided, to get this issue resolved.

Regards,

**- Foluso**

**Comment by Adekoreday** [comment]
Thanks for your response.

I have already done this since there are two overloads of the `Initialize` method in the TransactionApi.cs class.
Just curious, is there a reason why you didn't include the callback url in the shorter version of `initialize`

**Comment by adebisi-fa** [comment]
Hello @Adekoreday,

Paystack makes it possible for a developer to set a **global CallbackUrl** from the **Settings** section on the account dashboard.  As such, specifying a **different CallbackUrl** when initializing new transactions is **optional**, and only necessary when the global value is to be overwritten.

Since the shorter version of `_api.Initialize(...)` is meant to help the very basic usage of initialize endpoint, the `CallbackUrl`was omitted.

Hope this helps.

Regards.

**- Foluso**

**Comment by Adekoreday** [comment]
Nice, thanks. it does.
