### ISSUE TITLE
Not Charging my card

### ISSUE THREAD

**Issue by Ngozi-Anntex** [adebisi-fa/paystack-dotnet#19]
Am using the latest version but not charging any card, in my VB.NET application

**Comment by adebisi-fa** [comment]
Hello @Ngozi-Anntex ,

Which Paystack API/endpoint are you using please?

**Comment by Ngozi-Anntex** [comment]
v0.7.7.0
Am integrating it with my VB.Net Application
It works fine with test cards but not with actual cards

**Comment by Ngozi-Anntex** [comment]
![paystack_capture](https://user-images.githubusercontent.com/69394336/89714132-83edac00-d994-11ea-8375-a580de459fda.PNG)

**Comment by adebisi-fa** [comment]
If it works fine with test card, then it should be OK with the real one.

Some suggestions to try:

- Have you been able to use your card online, in the past?

- Is Live! mode available for your paystack account (you can check on your dashboard.)

Hope this helps.

Foluso.

**Comment by Ngozi-Anntex** [comment]
I use my card often online.
Not only my card, my clients cards too
It keep saying "could not complete transaction" on my Paystack dashboard
Have launched this application for two weeks now and the same for all output
My android app is working perfectly with their Paystack API, so it isn't from Paystack
And my account is Live.

**Comment by adebisi-fa** [comment]
I'll review the card endpoint for any issue, and update this thread.

Thanks for reporting, please.

Regards.


Foluso.

**Comment by Ngozi-Anntex** [comment]
Ok.
Thanks.
I will be waiting...

**Comment by Ngozi-Anntex** [comment]
Hi, good morning
I need to know if it has been fixed...

**Comment by adebisi-fa** [comment]
Dear @Ngozi-Anntex ,

Trust you're good today!

Sorry this is coming much later. 

I did looked into the possibility of any issue with this library's charge API (card), and found none.

A careful look at the subject shows that `Paystack` is discouraging `services/systems` sending card information through their API, unless such service/system has been "opted in" or "enabled", as it were.  In their words, [on this page](https://paystack.com/docs/payments/payment-channels/#cards):

> We strongly discourage passing card information directly to the API to avoid transmitting card data through systems that are not PCI compliant.
> 
> If you are PCI-DSS certified and would like to be able to send cardholder information directly to our APIs from your servers, reach out to us!

So, while it may work in the test environment like you mentioned, it may not work in production.

You mentioned that you use their API in your Android project, and it worked.  Well this might be because they found a more secure way to collect and protect the card information before forwarding through the API, in that native environment.

As a way, forward, kindly reach out to Paystack [here](https://paystack.com/contact/support) to resolve this.

Hope this helps.


**Foluso.**

**Comment by Ngozi-Anntex** [comment]
OK. Thanks
I will reach out to them...
